import { RedeCompany, CaseStudy } from "@terus/types";

export const RESULTADOS_OPERACIONAIS = [
  {
    title: "Digitalização do Canal",
    before: "0%",
    after: "até 96%",
    improvement: "Pedidos realizados digitalmente através da operação Terus.",
  },
  {
    title: "Ticket Médio",
    before: "R$ 1.740",
    after: "R$ 2.338",
    improvement: "+34% de crescimento no valor médio por pedido.",
  },
  {
    title: "Receita Processada",
    before: "R$ 11,6 mi",
    after: "R$ 16,0 mi",
    improvement:
      "+38% de crescimento financeiro no mesmo horizonte operacional.",
  },
  {
    title: "Rastreabilidade",
    value: "31.881 pedidos",
    description: "Auditoria ponta a ponta entre varejo, Terus e ERP.",
  },
];

export const INDICADORES_PLATAFORMA = [
  {
    title: "Rejeição ERP",
    value: "35% → 0,5%",
    description: "Redução significativa na rejeição de pedidos.",
  },
  {
    title: "Fill Rate",
    value: "40% → 96%",
    description: "Melhoria no atendimento de pedidos.",
  },
  {
    title: "Pedidos Rastreáveis",
    value: "31.881",
    description: "Pedidos identificados pela marca Terus no ERP.",
  },
  {
    title: "Digitalização Operacional",
    value: "86% a 96%",
    description: "Pedidos realizados via Terus.",
  },
];

export const EMPRESAS_CLIENTES: RedeCompany[] = [
  {
    name: "Cometa Supermercados",
    slug: "cometa-supermercados",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "RMS",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/cometa.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Supermercado Guará",
    slug: "supermercado-guara",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/guara.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Baratão Supermercados",
    slug: "baratao-supermercados",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: "https://barataosupermercados.com.br",
    featured: true,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/baratao.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Center Box",
    slug: "center-box",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "RMS",
    website: "https://centerbox.com.br",
    featured: true,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/centerbox.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Fazendinha",
    slug: "fazendinha",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: "https://www.supermercado-fazendinha.com.br",
    featured: true,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/fazendinha.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "São Luiz",
    slug: "saoluiz",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "RMS",
    website: "https://www.mercadinhossaoluiz.com.br",
    featured: true,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/saoluiz.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Super do Povo",
    slug: "super-do-povo",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/superdopovo.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Pinheiro Supermercados",
    slug: "pinheiro-supermercados",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/pinheiro.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Freitas Varejo",
    slug: "freitas-varejo",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/freitas.webp",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Frangolândia Supermercados",
    slug: "frangolandia-supermercados",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/frangolandia.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Super Lagoa",
    slug: "super-lagoa",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/superlagoa.png",
      monochrome: null,
      dark: null,
    },
  },
];

export const DEPOIMENTOS = [
  {
    name: "Em atualização",
    role: "Em atualização",
    company: "Em atualização",
    testimonial: "Em atualização",
    avatar: null,
  },
  {
    name: "Em atualização",
    role: "Em atualização",
    company: "Em atualização",
    testimonial: "Em atualização",
    avatar: null,
  },
  {
    name: "Em atualização",
    role: "Em atualização",
    company: "Em atualização",
    testimonial: "Em atualização",
    avatar: null,
  },
];

export const CASES_DE_SUCESSO = [
  {
    title: "Em atualização",
    company: "Em atualização",
    description: "Em atualização",
    results: "Em atualização",
    image: null,
  },
  {
    title: "Em atualização",
    company: "Em atualização",
    description: "Em atualização",
    results: "Em atualização",
    image: null,
  },
  {
    title: "Em atualização",
    company: "Em atualização",
    description: "Em atualização",
    results: "Em atualização",
    image: null,
  },
];

export const INTEGRACOES = [
  {
    name: "Em atualização",
    type: "ERP",
    description: "Em atualização",
    logo: null,
  },
  {
    name: "Em atualização",
    type: "ERP",
    description: "Em atualização",
    logo: null,
  },
  {
    name: "Em atualização",
    type: "Conector",
    description: "Em atualização",
    logo: null,
  },
  {
    name: "Em atualização",
    type: "API",
    description: "Em atualização",
    logo: null,
  },
];

export const CERTIFICACOES = [
  {
    name: "Em atualização",
    issuer: "Em atualização",
    description: "Em atualização",
    logo: null,
  },
  {
    name: "Em atualização",
    issuer: "Em atualização",
    description: "Em atualização",
    logo: null,
  },
  {
    name: "Em atualização",
    issuer: "Em atualização",
    description: "Em atualização",
    logo: null,
  },
];

export const VAREJOS: RedeCompany[] = [
  {
    name: "Baratão Supermercados",
    slug: "baratao-supermercados",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: "https://barataosupermercados.com.br",
    featured: true,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/baratao.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Center Box",
    slug: "center-box",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "RMS",
    website: "https://centerbox.com.br",
    featured: true,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/centerbox.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Cometa Supermercados",
    slug: "cometa-supermercados",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "RMS",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/cometa.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Fazendinha",
    slug: "fazendinha",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: "https://www.supermercado-fazendinha.com.br",
    featured: true,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/fazendinha.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Frangolândia Supermercados",
    slug: "frangolandia-supermercados",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "public",
    logos: {
      primary: null,
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Freitas Varejo",
    slug: "freitas-varejo",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "public",
    logos: {
      primary: null,
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Nova Opção Supermercados",
    slug: "nova-opcao-supermercados",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/novaopcao.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Pinheiro Supermercados",
    slug: "pinheiro-supermercados",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "public",
    logos: {
      primary: null,
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "São Luiz",
    slug: "saoluiz",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "RMS",
    website: "https://www.mercadinhossaoluiz.com.br",
    featured: true,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/saoluiz.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Super do Povo",
    slug: "super-do-povo",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/superdopovo.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Pinheiro Supermercados",
    slug: "pinheiro-supermercados",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/pinheiro.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Freitas Varejo",
    slug: "freitas-varejo",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/freitas.webp",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Frangolândia Supermercados",
    slug: "frangolandia-supermercados",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/frangolandia.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Super Lagoa",
    slug: "super-lagoa",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/superlagoa.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Supermercado Guará",
    slug: "supermercado-guara",
    category: "varejo",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/clientes/guara.png",
      monochrome: null,
      dark: null,
    },
  },
];

export const DISTRIBUIDORES: RedeCompany[] = [
  {
    name: "Brava Distribuidora",
    slug: "brava-distribuidora",
    category: "distribuidor",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/distribuidores/brava.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Distribuidora Asa Branca",
    slug: "distribuidora-asa-branca",
    category: "distribuidor",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/distribuidores/asabranca.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Donizete Distribuidora",
    slug: "donizete-distribuidora",
    category: "distribuidor",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/distribuidores/donizete.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "D'Origem Distribuidora",
    slug: "dorigem-distribuidora",
    category: "distribuidor",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/distribuidores/dorigem.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "JA Distribuidora",
    slug: "ja-distribuidora",
    category: "distribuidor",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/distribuidores/ja.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "Opção Distribuidora",
    slug: "opcao-distribuidora",
    category: "distribuidor",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/distribuidores/opcao.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "RB Distribuidora",
    slug: "rb-distribuidora",
    category: "distribuidor",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/distribuidores/rb.png",
      monochrome: null,
      dark: null,
    },
  },
  {
    name: "DSL Distribuidora",
    slug: "dsl-distribuidora",
    category: "distribuidor",
    status: "ativo",
    integrationStatus: "connected",
    erp: "Winthor",
    website: null,
    featured: false,
    permissionLevel: "logo",
    logos: {
      primary: "/logos/distribuidores/dsl.png",
      monochrome: null,
      dark: null,
    },
  },
];

export const REDE_TERUS = {
  varejos: VAREJOS,
  distribuidores: DISTRIBUIDORES,
};

export const VIDEOS_INSTITUCIONAIS = [
  {
    title: "Apresentação Institucional",
    description: "Em atualização",
    thumbnail: null,
    videoUrl: null,
  },
  {
    title: "Visão da Plataforma",
    description: "Em atualização",
    thumbnail: null,
    videoUrl: null,
  },
  {
    title: "Transformação Operacional",
    description: "Em atualização",
    thumbnail: null,
    videoUrl: null,
  },
];

export const VIDEOS_EDUCACIONAIS = [
  {
    title: "Terus Alert",
    description: "Em atualização",
    thumbnail: null,
    videoUrl: null,
  },
  {
    title: "Terus Order",
    description: "Em atualização",
    thumbnail: null,
    videoUrl: null,
  },
  {
    title: "Terus Task",
    description: "Em atualização",
    thumbnail: null,
    videoUrl: null,
  },
  {
    title: "Terus Pulse",
    description: "Em atualização",
    thumbnail: null,
    videoUrl: null,
  },
];

export const CONTEUDOS_INSTITUCIONAIS = [
  {
    title: "Apresentação Institucional",
    description: "Em atualização",
    thumbnail: null,
    contentUrl: null,
    type: "video",
  },
  {
    title: "Visão da Plataforma",
    description: "Em atualização",
    thumbnail: null,
    contentUrl: null,
    type: "video",
  },
  {
    title: "Nossa História",
    description: "Em atualização",
    thumbnail: null,
    contentUrl: null,
    type: "video",
  },
  {
    title: "Transformação Operacional",
    description: "Em atualização",
    thumbnail: null,
    contentUrl: null,
    type: "video",
  },
];

export const CONTEUDOS_EDUCACIONAIS = [
  {
    title: "Ruptura e Disponibilidade",
    description: "Em atualização",
    thumbnail: null,
    contentUrl: null,
    type: "video",
  },
  {
    title: "Reposição Inteligente",
    description: "Em atualização",
    thumbnail: null,
    contentUrl: null,
    type: "video",
  },
  {
    title: "Execução Operacional",
    description: "Em atualização",
    thumbnail: null,
    contentUrl: null,
    type: "video",
  },
  {
    title: "Monitoramento Contínuo",
    description: "Em atualização",
    thumbnail: null,
    contentUrl: null,
    type: "video",
  },
  {
    title: "Governança Operacional",
    description: "Em atualização",
    thumbnail: null,
    contentUrl: null,
    type: "video",
  },
  {
    title: "Supply Chain Intelligence",
    description: "Em atualização",
    thumbnail: null,
    contentUrl: null,
    type: "video",
  },
];

export const CONTEUDOS_MODULOS = [
  {
    title: "Terus Alert",
    description: "Em atualização",
    thumbnail: null,
    contentUrl: null,
    type: "video",
  },
  {
    title: "Terus Strategy",
    description: "Em atualização",
    thumbnail: null,
    contentUrl: null,
    type: "video",
  },
  {
    title: "Terus Order",
    description: "Em atualização",
    thumbnail: null,
    contentUrl: null,
    type: "video",
  },
  {
    title: "Terus Task",
    description: "Em atualização",
    thumbnail: null,
    contentUrl: null,
    type: "video",
  },
  {
    title: "Terus Log",
    description: "Em atualização",
    thumbnail: null,
    contentUrl: null,
    type: "video",
  },
  {
    title: "Terus Pulse",
    description: "Em atualização",
    thumbnail: null,
    contentUrl: null,
    type: "video",
  },
];

export const CONTEUDOS_CASES: CaseStudy[] = [
  {
    slug: "crescimento-operacional-distribuidor-terus",
    title: "Crescimento operacional em distribuidor da Rede Terus",
    company: null,
    category: "distribuidor",
    erp: "Winthor",
    challenge:
      "Baixa digitalização, alto índice de rejeição ERP e baixo atendimento de pedidos.",
    implementation: "Adoção da jornada operacional Terus integrada ao Winthor.",
    results:
      "Digitalização de até 96% dos pedidos, Rejeição ERP reduzida para 0,5%, Fill Rate elevado para 96%, Ticket médio +34%, Receita processada +38%, Mais de 31 mil pedidos rastreáveis.",
    thumbnail: null,
    description:
      "Crescimento operacional em distribuidor da Rede Terus obtendo digitalização de até 96%.",
    beforeAfterIndicators: {
      antes: [
        { label: "Digitalização do canal", value: "0%" },
        { label: "Rejeição ERP", value: "35%" },
        { label: "Fill Rate", value: "40%" },
        { label: "Ticket Médio", value: "R$ 1.740" },
      ],
      depois: [
        { label: "Digitalização do canal", value: "até 96%" },
        { label: "Rejeição ERP", value: "0,5%" },
        { label: "Fill Rate", value: "96%" },
        { label: "Ticket Médio", value: "R$ 2.338" },
      ],
      resultados: [
        { label: "Ticket Médio", value: "+34%" },
        { label: "Receita Processada", value: "+38%" },
        { label: "Pedidos Rastreáveis", value: "31.881" },
      ],
    },
    executiveIndicators: [
      {
        label: "Ticket Médio",
        value: "R$ 1.740 → R$ 2.338",
        description: "Crescimento de valor médio por pedido",
      },
      {
        label: "Receita Processada",
        value: "R$ 11,6 mi → R$ 16,0 mi",
        description: "Evolução do faturamento financeiro",
      },
      {
        label: "Fill Rate",
        value: "40% → 96%",
        description: "Aumento no nível de atendimento de produtos",
      },
      {
        label: "Rejeição ERP",
        value: "35% → 0,5%",
        description: "Redução drástica de falhas operacionais e de validação",
      },
      {
        label: "Pedidos Rastreáveis",
        value: "31.881",
        description: "Total auditado ponta a ponta",
      },
      {
        label: "Digitalização Operacional",
        value: "86% a 96%",
        description: "Volume de pedidos gerados de forma digital",
      },
    ],
    logos: {
      primary: null,
      monochrome: null,
      dark: null,
    },
  },
];
